version: "3"
services:
  server:
    image: docker
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/construction
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=construction

networks:
  springmysql-net: